(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},p=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),q="function"==
typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},r=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&q(c,a,{configurable:!0,writable:!0,value:b})}};
r("Symbol",function(a){if(a)return a;var b=function(e,f){this.Ba=e;q(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.Ba};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&q(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},t=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
r("WeakMap",function(a){function b(){}function c(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function d(k){if(!t(k,f)){var l=new b;q(k,f,{value:l})}}function e(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof b)return m;Object.isExtensible(m)&&d(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(K){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,g=function(k){this.g=(h+=Math.random()+1).toString();if(k){k=p(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};g.prototype.set=function(k,l){if(!c(k))throw Error("Invalid WeakMap key");d(k);if(!t(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};g.prototype.get=function(k){return c(k)&&t(k,f)?k[f][this.g]:void 0};g.prototype.has=function(k){return c(k)&&t(k,f)&&t(k[f],this.g)};
g.prototype.delete=function(k){return c(k)&&t(k,f)&&t(k[f],this.g)?delete k[f][this.g]:!1};return g});
r("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),k=new a(p([[g,"s"]]));if("s"!=k.get(g)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=g||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x||"t"!=m.value[1]||!l.next().done?!1:!0}catch(K){return!1}}())return a;var b=new WeakMap,c=function(g){this.K={};this.f=f();
this.size=0;if(g){g=p(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(g,k){g=0===g?0:g;var l=d(this,g);l.list||(l.list=this.K[l.id]=[]);l.c?l.c.value=k:(l.c={next:this.f,l:this.f.l,head:this.f,key:g,value:k},l.list.push(l.c),this.f.l.next=l.c,this.f.l=l.c,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.c&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.K[g.id],g.c.l.next=g.c.next,g.c.next.l=g.c.l,g.c.head=null,this.size--,
!0):!1};c.prototype.clear=function(){this.K={};this.f=this.f.l=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).c};c.prototype.get=function(g){return(g=d(this,g).c)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,function(g){return g.value})};c.prototype.forEach=function(g,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,
g.call(k,m[1],m[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,k){var l=k&&typeof k;"object"==l||"function"==l?b.has(k)?l=b.get(k):(l=""+ ++h,b.set(k,l)):l="p_"+k;var m=g.K[l];if(m&&t(g.K,l))for(g=0;g<m.length;g++){var K=m[g];if(k!==k&&K.key!==K.key||k===K.key)return{id:l,list:m,index:g,c:K}}return{id:l,list:m,index:-1,c:void 0}},e=function(g,k){var l=g.f;return da(function(){if(l){for(;l.head!=g.f;)l=l.l;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,
value:void 0}})},f=function(){var g={};return g.l=g.next=g.head=g},h=0;return c});
var u=this||self,ea=/^[\w+/_-]+[=]{0,2}$/,fa=null,ha=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&ea.test(a)?a:""},v=function(){},ia=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},ja=function(a){var b=ia(a);return"array"==b||"object"==b&&"number"==typeof a.length},w=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ka=function(a,b,c){return a.call.apply(a.bind,arguments)},la=
function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},x=function(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ka:la;return x.apply(null,arguments)},y=function(a,b){function c(){}c.prototype=b.prototype;a.O=b.prototype;a.prototype=new c;
a.prototype.constructor=a;a.ab=function(d,e,f){for(var h=Array(arguments.length-2),g=2;g<arguments.length;g++)h[g-2]=arguments[g];return b.prototype[e].apply(d,h)}},ma=function(a){return a};var z=function(a,b){this.width=a;this.height=b};n=z.prototype;n.clone=function(){return new z(this.width,this.height)};n.toString=function(){return"("+this.width+" x "+this.height+")"};n.aspectRatio=function(){return this.width/this.height};n.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};n.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
n.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};n.scale=function(a,b){this.width*=a;this.height*="number"===typeof b?b:a;return this};var na=function(a,b){for(var c in a)b.call(void 0,a[c],c,a)},oa=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1},pa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),qa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<pa.length;f++)c=pa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var sa=function(){var a=ra.play_url;this.v=ra.format_id;this.Va=a},ta={Ya:7,Za:18,Xa:22,$a:37},ua=[7,18,22,37],va=new Map([[7,new z(320,240)],[18,new z(640,360)],[22,new z(1280,720)],[37,new z(1920,1080)]]);function A(a){if(Error.captureStackTrace)Error.captureStackTrace(this,A);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}y(A,Error);A.prototype.name="CustomError";var wa;var xa=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");A.call(this,c+a[d])};y(xa,A);xa.prototype.name="AssertionError";
var ya=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new xa(""+e,f||[]);},B=function(a,b,c){a||ya("",null,b,Array.prototype.slice.call(arguments,2))},za=function(a,b){throw new xa("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},Aa=function(a,b,c){"function"!==typeof a&&ya("Expected function but got %s: %s.",[ia(a),a],b,Array.prototype.slice.call(arguments,2))};var Ba=Array.prototype.indexOf?function(a,b){B(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ca=Array.prototype.forEach?function(a,b,c){B(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Da=Array.prototype.filter?
function(a,b){B(null!=a.length);return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var g=f[h];b.call(void 0,g,h,a)&&(d[e++]=g)}return d},Ea=Array.prototype.some?function(a,b){B(null!=a.length);return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};
function Fa(a,b){b=Ba(a,b);var c;if(c=0<=b)B(null!=a.length),Array.prototype.splice.call(a,b,1);return c}function Ga(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ha(a,b){a.sort(b||Ia)}function Ia(a,b){return a>b?1:a<b?-1:0};var Ja=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Ka=/&/g,La=/</g,Ma=/>/g,Na=/"/g,Oa=/'/g,Pa=/\x00/g,Qa=/[\x00&<>"']/,Ra=function(a,b){return a<b?-1:a>b?1:0};var C;a:{var Sa=u.navigator;if(Sa){var Ta=Sa.userAgent;if(Ta){C=Ta;break a}}C=""}var D=function(a){return-1!=C.indexOf(a)};var Ua;var E=function(a,b){this.na=a===Va&&b||"";this.Ca=Wa};E.prototype.xa=!0;E.prototype.va=function(){return this.na};E.prototype.toString=function(){return"Const{"+this.na+"}"};var Wa={},Va={};var F=function(a,b){this.ka=b===Xa?a:""};F.prototype.xa=!0;F.prototype.va=function(){return this.ka.toString()};F.prototype.toString=function(){return"TrustedResourceUrl{"+this.ka+"}"};var Ya=function(a){if(a instanceof F&&a.constructor===F)return a.ka;za("expected object of type TrustedResourceUrl, got '"+a+"' of type "+ia(a));return"type_error:TrustedResourceUrl"},Xa={};var Za=function(a,b){a:{try{var c=a&&a.ownerDocument,d=c&&(c.defaultView||c.parentWindow);d=d||u;if(d.Element&&d.Location){var e=d;break a}}catch(h){}e=null}if(e&&"undefined"!=typeof e.HTMLScriptElement&&(!a||!(a instanceof e.HTMLScriptElement)&&(a instanceof e.Location||a instanceof e.Element))){if(w(a))try{var f=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(h){f="<object could not be stringified>"}else f=void 0===a?"undefined":null===a?"null":typeof a;za("Argument is not a %s (or a non-Element, non-Location mock); got: %s",
"HTMLScriptElement",f)}a.src=Ya(b);(b=a.ownerDocument&&a.ownerDocument.defaultView)&&b!=u?b=ha(b.document):(null===fa&&(fa=ha(u.document)),b=fa);b&&a.setAttribute("nonce",b)};var $a=function(a){Qa.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(Ka,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(La,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(Ma,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(Na,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(Oa,"&#39;")),-1!=a.indexOf("\x00")&&(a=a.replace(Pa,"&#0;")));return a},ab=function(){return"background-image".replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()})},cb=function(){return bb.replace(/(^|[\s]+)([a-z])/g,function(a,b,c){return b+c.toUpperCase()})};var db=function(a){db[" "](a);return a};db[" "]=v;var eb=D("Opera"),G=D("Trident")||D("MSIE"),fb=D("Edge"),gb=D("Gecko")&&!(-1!=C.toLowerCase().indexOf("webkit")&&!D("Edge"))&&!(D("Trident")||D("MSIE"))&&!D("Edge"),hb=-1!=C.toLowerCase().indexOf("webkit")&&!D("Edge"),ib=function(){var a=u.document;return a?a.documentMode:void 0},jb;
a:{var kb="",lb=function(){var a=C;if(gb)return/rv:([^\);]+)(\)|;)/.exec(a);if(fb)return/Edge\/([\d\.]+)/.exec(a);if(G)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(hb)return/WebKit\/(\S+)/.exec(a);if(eb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();lb&&(kb=lb?lb[1]:"");if(G){var mb=ib();if(null!=mb&&mb>parseFloat(kb)){jb=String(mb);break a}}jb=kb}var nb=jb,ob={},pb;if(u.document&&G){var qb=ib();pb=qb?qb:parseInt(nb,10)||void 0}else pb=void 0;var rb=pb;var sb=Object.freeze||function(a){return a};var tb=!G||9<=Number(rb),ub;
if(ub=G){var vb;if(Object.prototype.hasOwnProperty.call(ob,"9"))vb=ob["9"];else{for(var wb=0,xb=Ja(String(nb)).split("."),yb=Ja("9").split("."),zb=Math.max(xb.length,yb.length),Ab=0;0==wb&&Ab<zb;Ab++){var Bb=xb[Ab]||"",Cb=yb[Ab]||"";do{var H=/(\d*)(\D*)(.*)/.exec(Bb)||["","","",""],I=/(\d*)(\D*)(.*)/.exec(Cb)||["","","",""];if(0==H[0].length&&0==I[0].length)break;wb=Ra(0==H[1].length?0:parseInt(H[1],10),0==I[1].length?0:parseInt(I[1],10))||Ra(0==H[2].length,0==I[2].length)||Ra(H[2],I[2]);Bb=H[3];
Cb=I[3]}while(0==wb)}vb=ob["9"]=0<=wb}ub=!vb}var Db=ub,Eb=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",v,b),u.removeEventListener("test",v,b)}catch(c){}return a}();var Fb=function(){};var J=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.B=!1};J.prototype.stopPropagation=function(){this.B=!0};J.prototype.preventDefault=function(){this.defaultPrevented=!0};var L=function(a,b){J.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.M=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=
b;if(b=a.relatedTarget){if(gb){a:{try{db(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.offsetX=hb||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=hb||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,
this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Gb[a.pointerType]||"";this.state=a.state;this.M=a;a.defaultPrevented&&this.preventDefault()}};
y(L,J);var Gb=sb({2:"touch",3:"pen",4:"mouse"});L.prototype.stopPropagation=function(){L.O.stopPropagation.call(this);this.M.stopPropagation?this.M.stopPropagation():this.M.cancelBubble=!0};L.prototype.preventDefault=function(){L.O.preventDefault.call(this);var a=this.M;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Db)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var M="closure_listenable_"+(1E6*Math.random()|0),Hb=0;var Ib=function(a,b,c,d,e){this.listener=a;this.Y=null;this.src=b;this.type=c;this.capture=!!d;this.V=e;this.key=++Hb;this.I=this.S=!1},Jb=function(a){a.I=!0;a.listener=null;a.Y=null;a.src=null;a.V=null};var N=function(a){this.src=a;this.b={};this.P=0};N.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.b[f];a||(a=this.b[f]=[],this.P++);var h=Kb(a,b,d,e);-1<h?(b=a[h],c||(b.S=!1)):(b=new Ib(b,this.src,f,!!d,e),b.S=c,a.push(b));return b};N.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.b))return!1;var e=this.b[a];b=Kb(e,b,c,d);return-1<b?(Jb(e[b]),B(null!=e.length),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.b[a],this.P--),!0):!1};
var Lb=function(a,b){var c=b.type;c in a.b&&Fa(a.b[c],b)&&(Jb(b),0==a.b[c].length&&(delete a.b[c],a.P--))},Mb=function(a){var b=0,c;for(c in a.b){for(var d=a.b[c],e=0;e<d.length;e++)++b,Jb(d[e]);delete a.b[c];a.P--}};N.prototype.ha=function(a,b,c,d){a=this.b[a.toString()];var e=-1;a&&(e=Kb(a,b,c,d));return-1<e?a[e]:null};
N.prototype.hasListener=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return oa(this.b,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};var Kb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.I&&f.listener==b&&f.capture==!!c&&f.V==d)return e}return-1};var Nb="closure_lm_"+(1E6*Math.random()|0),Ob={},Pb=0,Rb=function(a,b,c,d,e){if(d&&d.once)Qb(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)Rb(a,b[f],c,d,e);else c=Sb(c),a&&a[M]?(d=w(d)?!!d.capture:!!d,Tb(a),a.j.add(String(b),c,!1,d,e)):Ub(a,b,c,!1,d,e)},Ub=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=w(e)?!!e.capture:!!e,g=Vb(a);g||(a[Nb]=g=new N(a));c=g.add(b,c,d,h,f);if(!c.Y){d=Wb();c.Y=d;d.src=a;d.listener=c;if(a.addEventListener)Eb||(e=h),void 0===e&&(e=
!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Xb(b.toString()),d);else if(a.addListener&&a.removeListener)B("change"===b,"MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Pb++}},Wb=function(){var a=Yb,b=tb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},Qb=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Qb(a,
b[f],c,d,e);else c=Sb(c),a&&a[M]?a.j.add(String(b),c,!0,w(d)?!!d.capture:!!d,e):Ub(a,b,c,!0,d,e)},Zb=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Zb(a,b[f],c,d,e);else d=w(d)?!!d.capture:!!d,c=Sb(c),a&&a[M]?a.j.remove(String(b),c,d,e):a&&(a=Vb(a))&&(b=a.ha(b,c,d,e))&&$b(b)},$b=function(a){if("number"!==typeof a&&a&&!a.I){var b=a.src;if(b&&b[M])Lb(b.j,a);else{var c=a.type,d=a.Y;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Xb(c),d):b.addListener&&
b.removeListener&&b.removeListener(d);Pb--;(c=Vb(b))?(Lb(c,a),0==c.P&&(c.src=null,b[Nb]=null)):Jb(a)}}},Xb=function(a){return a in Ob?Ob[a]:Ob[a]="on"+a},bc=function(a,b,c,d){var e=!0;if(a=Vb(a))if(b=a.b[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.I&&(f=ac(f,d),e=e&&!1!==f)}return e},ac=function(a,b){var c=a.listener,d=a.V||a.src;a.S&&$b(a);return c.call(d,b)},Yb=function(a,b){if(a.I)return!0;if(!tb){if(!b)a:{b=["window","event"];for(var c=u,d=0;d<b.length;d++)if(c=
c[b[d]],null==c){b=null;break a}b=c}d=b;b=new L(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.currentTarget;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.B&&0<=e;e--){b.currentTarget=d[e];var f=bc(d[e],a,!0,b);c=c&&f}for(e=0;!b.B&&e<d.length;e++)b.currentTarget=d[e],f=bc(d[e],a,!1,b),c=c&&f}return c}return ac(a,new L(b,this))},Vb=function(a){a=a[Nb];return a instanceof
N?a:null},cc="__closure_events_fn_"+(1E9*Math.random()>>>0),Sb=function(a){B(a,"Listener can not be null.");if("function"===typeof a)return a;B(a.handleEvent,"An object listener must have handleEvent method.");a[cc]||(a[cc]=function(b){return a.handleEvent(b)});return a[cc]};var dc=!G||9<=Number(rb);var fc=function(a,b){na(b,function(c,d){c&&"object"==typeof c&&c.xa&&(c=c.va());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:ec.hasOwnProperty(d)?a.setAttribute(ec[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})},ec={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",
width:"width"},gc=function(a,b,c,d){function e(g){g&&b.appendChild("string"===typeof g?a.createTextNode(g):g)}for(;d<c.length;d++){var f=c[d];if(!ja(f)||w(f)&&0<f.nodeType)e(f);else{a:{if(f&&"number"==typeof f.length){if(w(f)){var h="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){h="function"==typeof f.item;break a}}h=!1}Ca(h?Ga(f):f,e)}}},hc=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},ic=function(a){return a&&
a.parentNode?a.parentNode.removeChild(a):null},jc=function(){this.L=u.document||document};n=jc.prototype;n.ua=function(){};n.getElementsByTagName=function(a,b){return(b||this.L).getElementsByTagName(String(a))};
n.T=function(a,b,c){var d=this.L,e=arguments,f=String(e[0]),h=e[1];if(!dc&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',$a(h.name),'"');if(h.type){f.push(' type="',$a(h.type),'"');var g={};qa(g,h);delete g.type;h=g}f.push(">");f=f.join("")}f=hc(d,f);h&&("string"===typeof h?f.className=h:Array.isArray(h)?f.className=h.join(" "):fc(f,h));2<e.length&&gc(d,f,e,2)};n.createElement=function(a){return hc(this.L,a)};n.createTextNode=function(a){return this.L.createTextNode(String(a))};
n.appendChild=function(a,b){B(null!=a&&null!=b,"goog.dom.appendChild expects non-null arguments");a.appendChild(b)};n.append=function(a,b){var c=a;B(c,"Node cannot be null or undefined.");gc(9==c.nodeType?c:c.ownerDocument||c.document,a,arguments,1)};n.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
n.removeNode=ic;n.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var O=function(){this.j=new N(this);this.Da=this;this.ja=null};y(O,Fb);O.prototype[M]=!0;O.prototype.la=function(a){this.ja=a};O.prototype.addEventListener=function(a,b,c,d){Rb(this,a,b,c,d)};O.prototype.removeEventListener=function(a,b,c,d){Zb(this,a,b,c,d)};
O.prototype.dispatchEvent=function(a){Tb(this);var b=this.ja;if(b){var c=[];for(var d=1;b;b=b.ja)c.push(b),B(1E3>++d,"infinite loop")}b=this.Da;d=a.type||a;if("string"===typeof a)a=new J(a,b);else if(a instanceof J)a.target=a.target||b;else{var e=a;a=new J(d,b);qa(a,e)}e=!0;if(c)for(var f=c.length-1;!a.B&&0<=f;f--){var h=a.currentTarget=c[f];e=kc(h,d,!0,a)&&e}a.B||(h=a.currentTarget=b,e=kc(h,d,!0,a)&&e,a.B||(e=kc(h,d,!1,a)&&e));if(c)for(f=0;!a.B&&f<c.length;f++)h=a.currentTarget=c[f],e=kc(h,d,!1,
a)&&e;return e};var kc=function(a,b,c,d){b=a.j.b[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var h=b[f];if(h&&!h.I&&h.capture==c){var g=h.listener,k=h.V||h.src;h.S&&Lb(a.j,h);e=!1!==g.call(k,d)&&e}}return e&&!d.defaultPrevented};O.prototype.ha=function(a,b,c,d){return this.j.ha(String(a),b,c,d)};O.prototype.hasListener=function(a,b){return this.j.hasListener(void 0!==a?String(a):void 0,b)};var Tb=function(a){B(a.j,"Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?")};var lc={};var P=function(){};P.ia=void 0;P.Ja=function(){return P.ia?P.ia:P.ia=new P};P.prototype.Oa=0;P.prototype.Ma="";var Q=function(a){O.call(this);a||(a=wa||(wa=new jc));this.sa=a;this.g=null;this.G=!1;this.u=null;this.wa=void 0;this.da=this.ea=this.a=null};y(Q,O);n=Q.prototype;n.La=P.Ja();n.ua=function(){return this.u};n.getParent=function(){return this.a};n.la=function(a){if(this.a&&this.a!=a)throw Error("Method not supported");Q.O.la.call(this,a)};n.T=function(){this.u=this.sa.createElement("DIV")};
var nc=function(a){a.G=!0;mc(a,function(b){!b.G&&b.ua()&&nc(b)})},oc=function(a){mc(a,function(b){b.G&&oc(b)});a.wa&&Mb(a.wa);a.G=!1},mc=function(a,b){a.ea&&Ca(a.ea,b,void 0)};
Q.prototype.removeChild=function(a,b){if(a){if("string"!==typeof a){var c;(c=a.g)||(c=a.La,c=c.Ma+":"+(c.Oa++).toString(36),c=a.g=c);a=c}c=a;this.da&&c?(a=this.da,a=(null!==a&&c in a?a[c]:void 0)||null):a=null;if(c&&a){var d=this.da;c in d&&delete d[c];Fa(this.ea,a);b&&(oc(a),a.u&&ic(a.u));b=a;if(null==b)throw Error("Unable to set parent component");b.a=null;Q.O.la.call(b,null)}}if(!a)throw Error("Child is not in parent component");return a};var pc=function(a){Q.call(this,a)};y(pc,Q);pc.prototype.ta=function(){return null};var qc=function(a,b){this.Na=100;this.Ga=a;this.Ra=b;this.X=0;this.f=null};qc.prototype.get=function(){if(0<this.X){this.X--;var a=this.f;this.f=a.next;a.next=null}else a=this.Ga();return a};qc.prototype.put=function(a){this.Ra(a);this.X<this.Na&&(this.X++,a.next=this.f,this.f=a)};var rc=function(a){u.setTimeout(function(){throw a;},0)},sc,tc=function(){var a=u.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!D("Presto")&&(a=function(){var e=hc(document,"IFRAME");e.style.display="none";document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.close();var h="callImmediate"+Math.random(),g="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=x(function(k){if(("*"==
g||k.origin==g)&&k.data==h)this.port1.onmessage()},this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(h,g)}}});if("undefined"!==typeof a&&!D("Trident")&&!D("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.pa;c.pa=null;e()}};return function(e){d.next={pa:e};d=d.next;b.port2.postMessage(0)}}return function(e){u.setTimeout(e,0)}};var uc=function(){this.aa=this.C=null},wc=new qc(function(){return new vc},function(a){a.reset()});uc.prototype.add=function(a,b){var c=wc.get();c.set(a,b);this.aa?this.aa.next=c:(B(!this.C),this.C=c);this.aa=c};uc.prototype.remove=function(){var a=null;this.C&&(a=this.C,this.C=this.C.next,this.C||(this.aa=null),a.next=null);return a};var vc=function(){this.next=this.scope=this.ga=null};vc.prototype.set=function(a,b){this.ga=a;this.scope=b;this.next=null};
vc.prototype.reset=function(){this.next=this.scope=this.ga=null};var Bc=function(a,b){xc||yc();zc||(xc(),zc=!0);Ac.add(a,b)},xc,yc=function(){if(u.Promise&&u.Promise.resolve){var a=u.Promise.resolve(void 0);xc=function(){a.then(Cc)}}else xc=function(){var b=Cc;"function"!==typeof u.setImmediate||u.Window&&u.Window.prototype&&!D("Edge")&&u.Window.prototype.setImmediate==u.setImmediate?(sc||(sc=tc()),sc(b)):u.setImmediate(b)}},zc=!1,Ac=new uc,Cc=function(){for(var a;a=Ac.remove();){try{a.ga.call(a.scope)}catch(b){rc(b)}wc.put(a)}zc=!1};var Dc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var T=function(a){this.h=0;this.m=void 0;this.D=this.i=this.a=null;this.U=this.fa=!1;if(a!=v)try{var b=this;a.call(void 0,function(c){R(b,2,c)},function(c){if(!(c instanceof S))try{if(c instanceof Error)throw c;throw Error("Promise rejected.");}catch(d){}R(b,3,c)})}catch(c){R(this,3,c)}},Ec=function(){this.next=this.context=this.H=this.A=this.s=null;this.R=!1};Ec.prototype.reset=function(){this.context=this.H=this.A=this.s=null;this.R=!1};
var Fc=new qc(function(){return new Ec},function(a){a.reset()}),Gc=function(a,b,c){var d=Fc.get();d.A=a;d.H=b;d.context=c;return d};T.prototype.then=function(a,b,c){null!=a&&Aa(a,"opt_onFulfilled should be a function.");null!=b&&Aa(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return Hc(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};T.prototype.$goog_Thenable=!0;
T.prototype.cancel=function(a){if(0==this.h){var b=new S(a);Bc(function(){Ic(this,b)},this)}};
var Ic=function(a,b){if(0==a.h)if(a.a){var c=a.a;if(c.i){for(var d=0,e=null,f=null,h=c.i;h&&(h.R||(d++,h.s==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.h&&1==d?Ic(c,b):(f?(d=f,B(c.i),B(null!=d),d.next==c.D&&(c.D=d),d.next=d.next.next):Jc(c),Kc(c,e,3,b)))}a.a=null}else R(a,3,b)},Mc=function(a,b){a.i||2!=a.h&&3!=a.h||Lc(a);B(null!=b.A);a.D?a.D.next=b:a.i=b;a.D=b},Hc=function(a,b,c,d){var e=Gc(null,null,null);e.s=new T(function(f,h){e.A=b?function(g){try{var k=b.call(d,g);f(k)}catch(l){h(l)}}:f;
e.H=c?function(g){try{var k=c.call(d,g);void 0===k&&g instanceof S?h(g):f(k)}catch(l){h(l)}}:h});e.s.a=a;Mc(a,e);return e.s};T.prototype.Ta=function(a){B(1==this.h);this.h=0;R(this,2,a)};T.prototype.Ua=function(a){B(1==this.h);this.h=0;R(this,3,a)};
var R=function(a,b,c){if(0==a.h){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.h=1;a:{var d=c,e=a.Ta,f=a.Ua;if(d instanceof T){null!=e&&Aa(e,"opt_onFulfilled should be a function.");null!=f&&Aa(f,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");Mc(d,Gc(e||v,f||null,a));var h=!0}else if(Dc(d))d.then(e,f,a),h=!0;else{if(w(d))try{var g=d.then;if("function"===typeof g){Nc(d,g,e,f,a);h=!0;break a}}catch(k){f.call(a,k);h=
!0;break a}h=!1}}h||(a.m=c,a.h=b,a.a=null,Lc(a),3!=b||c instanceof S||Oc(a,c))}},Nc=function(a,b,c,d,e){var f=!1,h=function(k){f||(f=!0,c.call(e,k))},g=function(k){f||(f=!0,d.call(e,k))};try{b.call(a,h,g)}catch(k){g(k)}},Lc=function(a){a.fa||(a.fa=!0,Bc(a.Ia,a))},Jc=function(a){var b=null;a.i&&(b=a.i,a.i=b.next,b.next=null);a.i||(a.D=null);null!=b&&B(null!=b.A);return b};T.prototype.Ia=function(){for(var a;a=Jc(this);)Kc(this,a,this.h,this.m);this.fa=!1};
var Kc=function(a,b,c,d){if(3==c&&b.H&&!b.R)for(;a&&a.U;a=a.a)a.U=!1;if(b.s)b.s.a=null,Pc(b,c,d);else try{b.R?b.A.call(b.context):Pc(b,c,d)}catch(e){Qc.call(null,e)}Fc.put(b)},Pc=function(a,b,c){2==b?a.A.call(a.context,c):a.H&&a.H.call(a.context,c)},Oc=function(a,b){a.U=!0;Bc(function(){a.U&&Qc.call(null,b)})},Qc=rc,S=function(a){A.call(this,a)};y(S,A);S.prototype.name="cancel";/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var U=function(a){var b=Rc;this.Z=[];this.ya=b;this.ra=a||null;this.N=this.F=!1;this.m=void 0;this.ma=this.oa=this.ba=!1;this.$=0;this.a=null;this.ca=0};U.prototype.cancel=function(a){if(this.F)this.m instanceof U&&this.m.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.ca--,0>=b.ca&&b.cancel())}this.ya?this.ya.call(this.ra,this):this.ma=!0;this.F||Sc(this,new V(this))}};U.prototype.qa=function(a,b){this.ba=!1;Tc(this,a,b)};
var Tc=function(a,b,c){a.F=!0;a.m=c;a.N=!b;Uc(a)},Wc=function(a){if(a.F){if(!a.ma)throw new Vc(a);a.ma=!1}},Sc=function(a,b){Wc(a);Xc(b);Tc(a,!1,b)},Xc=function(a){B(!(a instanceof U),"An execution sequence may not be initiated with a blocking Deferred.")},Zc=function(a,b){Yc(a,b,null,void 0)},Yc=function(a,b,c,d){B(!a.oa,"Blocking Deferreds can not be re-used");a.Z.push([b,c,d]);a.F&&Uc(a)};
U.prototype.then=function(a,b,c){var d,e,f=new T(function(h,g){d=h;e=g});Yc(this,d,function(h){h instanceof V?f.cancel():e(h)});return f.then(a,b,c)};U.prototype.$goog_Thenable=!0;
var $c=function(a){return Ea(a.Z,function(b){return"function"===typeof b[1]})},Uc=function(a){if(a.$&&a.F&&$c(a)){var b=a.$,c=W[b];c&&(u.clearTimeout(c.g),delete W[b]);a.$=0}a.a&&(a.a.ca--,delete a.a);b=a.m;for(var d=c=!1;a.Z.length&&!a.ba;){var e=a.Z.shift(),f=e[0],h=e[1];e=e[2];if(f=a.N?h:f)try{var g=f.call(e||a.ra,b);void 0!==g&&(a.N=a.N&&(g==b||g instanceof Error),a.m=b=g);if(Dc(b)||"function"===typeof u.Promise&&b instanceof u.Promise)d=!0,a.ba=!0}catch(k){b=k,a.N=!0,$c(a)||(c=!0)}}a.m=b;d&&
(g=x(a.qa,a,!0),d=x(a.qa,a,!1),b instanceof U?(Yc(b,g,d),b.oa=!0):b.then(g,d));c&&(b=new ad(b),W[b.g]=b,a.$=b.g)},Vc=function(){A.call(this)};y(Vc,A);Vc.prototype.message="Deferred has already fired";Vc.prototype.name="AlreadyCalledError";var V=function(){A.call(this)};y(V,A);V.prototype.message="Deferred was canceled";V.prototype.name="CanceledError";var ad=function(a){this.g=u.setTimeout(x(this.Sa,this),0);this.Ha=a};
ad.prototype.Sa=function(){B(W[this.g],"Cannot throw an error that is not scheduled.");delete W[this.g];throw this.Ha;};var W={};var fd=function(){var a=bd,b={},c=b.document||document,d=Ya(a).toString(),e=hc(document,"SCRIPT"),f={za:e,Aa:void 0},h=new U(f),g=null,k=null!=b.timeout?b.timeout:5E3;0<k&&(g=window.setTimeout(function(){cd(e,!0);Sc(h,new dd(1,"Timeout reached for loading script "+d))},k),f.Aa=g);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(cd(e,b.bb||!1,g),Wc(h),Xc(null),Tc(h,!0,null))};e.onerror=function(){cd(e,!0,g);Sc(h,new dd(0,"Error while loading script "+
d))};f=b.attributes||{};qa(f,{type:"text/javascript",charset:"UTF-8"});fc(e,f);Za(e,a);ed(c).appendChild(e);return h},ed=function(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&0!=b.length?b[0]:a.documentElement},Rc=function(){if(this&&this.za){var a=this.za;a&&"SCRIPT"==a.tagName&&cd(a,!0,this.Aa)}},cd=function(a,b,c){null!=c&&u.clearTimeout(c);a.onload=v;a.onerror=v;a.onreadystatechange=v;b&&window.setTimeout(function(){ic(a)},0)},dd=function(a,b){var c="Jsloader error (code #"+
a+")";b&&(c+=": "+b);A.call(this,c);this.code=a};y(dd,A);var hd=function(a,b,c,d){Q.call(this,d);this.Wa=a;this.J=gd(b);c=c||{};this.Fa=!!c.autoplay;this.Ea=!!c.allow_resize;this.W=[]};y(hd,pc);var id;var X=new E(Va,"https://youtube.googleapis.com/iframe_api");X instanceof E&&X.constructor===E&&X.Ca===Wa?id=X.na:(za("expected object of type Const, got '"+X+"'"),id="type_error:Const");var jd=id,kd;
if(void 0===Ua){var ld=null,md=u.trustedTypes;if(md&&md.createPolicy)try{ld=md.createPolicy("goog#html",{createHTML:ma,createScript:ma,createScriptURL:ma})}catch(a){u.console&&u.console.error(a.message)}Ua=ld}var nd=(kd=Ua)?kd.createScriptURL(jd):jd,bd=new F(nd,Xa),od=new z(320,240),pd={7:"small",18:"medium",22:"hd720",37:"hd1080"},qd=new z(480,360),gd=function(a){a=Da(a,function(b){a:{for(var c in ta)if(ta[c]==b.v){b=!0;break a}b=!1}return b});Ha(a,function(b,c){return Ba(ua,b.v)-Ba(ua,c.v)});return a};
n=hd.prototype;n.ta=function(){var a=od.clone();var b=this.cb;if(b&&(b.width>=a.width||b.height>=a.height))a=b.clone();else{var c;b=this.eb;for(var d=0,e=this.J.length;d<e;d++){var f=va.get(this.J[d].v),h=f&&b&&(f.width>b.width||f.height>b.height);f&&(!c||f.width>c.width)&&!h&&(c=f)}c&&(c.width>=a.width||c.height>=a.height)&&(a=c.clone())}return new z(a.width,a.height+38)};n.T=function(){hd.O.T.call(this);Zc(fd(),x(function(){YT.ready(x(this.Pa,this))},this))};
n.Pa=function(){var a=this.ta();this.o=new YT.Player(this.Wa,{width:a.width,height:a.height,playerVars:{autohide:"1",enablecastapi:0,html5:"1",ps:"blogger"},events:{onStateChange:x(this.Ka,this),onReady:x(this.Qa,this)}});if(this.W){a=p(this.W);for(var b=a.next();!b.done;b=a.next())b=b.value,this.o.addEventListener(b.name,b.listener)}this.W=[]};n.Ka=function(a){this.dispatchEvent(new rd("b",a.data))};
n.Qa=function(){var a=this,b={fmt_list:sd(this),url_encoded_fmt_stream_map:td(this),video_id:"picasacid"};this.Ea&&(this.o.setSizeStyle(!0,!1),this.o.addEventListener("SIZE_CLICKED",function(c){a.o.setSizeStyle(!0,c.data)}));this.Fa?this.o.loadVideoByPlayerVars(b):this.o.cueVideoByPlayerVars(b)};
var sd=function(a){for(var b=[],c=0;c<a.J.length;++c)b.push(ud(a.J[c]));return b.reverse().join(",")},ud=function(a){var b=va.get(a.v);b||(b=qd);return a.v+"/"+b.width+"x"+b.height},td=function(a){for(var b=[],c=0;c<a.J.length;++c){var d=a.J[c],e=d.v;d="url="+encodeURIComponent(String(d.Va))+"&itag="+e+"&type="+encodeURIComponent("video/mp4;")+"&quality="+pd[e];b.push(d)}return b.reverse().join(",")},rd=function(a){J.call(this,a)};y(rd,J);var vd=u.document.getElementById("videocontainer");if(VIDEO_CONFIG.thumbnail){var wd=document.querySelector(".thumbnail-holder"),xd="url("+VIDEO_CONFIG.thumbnail+")",yd,Y=lc["background-image"];if(!Y){var bb=ab();Y=bb;if(void 0===wd.style[bb]){var zd=(hb?"Webkit":gb?"Moz":G?"ms":eb?"O":null)+cb();void 0!==wd.style[zd]&&(Y=zd)}lc["background-image"]=Y}(yd=Y)&&(wd.style[yd]=xd)}for(var Ad=[],Bd=p(VIDEO_CONFIG.streams),Cd=Bd.next();!Cd.done;Cd=Bd.next()){var ra=Cd.value;Ad.push(new sa)}
var Z=new hd(vd,Ad,{autoplay:!0,allow_resize:VIDEO_CONFIG.allow_resize});if(VIDEO_CONFIG.allow_resize&&VIDEO_CONFIG.iframe_id){var Dd=function(a){window.parent.postMessage({name:"video_resize",iframe_id:VIDEO_CONFIG.iframe_id,widescreen:a.data},document.referrer)};Z.o?Z.o.addEventListener("SIZE_CLICKED",Dd):Z.W.push({name:"SIZE_CLICKED",listener:Dd})}
Rb(vd,"click",function(){if(Z.G)throw Error("Component already rendered");Z.u||Z.T();vd?vd.insertBefore(Z.u,null):Z.sa.L.body.appendChild(Z.u);Z.a&&!Z.a.G||nc(Z)});}).call(this);